datasources:
  default:
    url: jdbc:tc:postgresql:12:///postgres
    driverClassName: org.testcontainers.jdbc.ContainerDatabaseDriver
    username: test
    password: test

micronaut:
  server:
    port: 0

endpoints:
  all:
    port: 0
    enabled: false

auth:
  passkey:
    rp-id: localhost
    rp-name: Apized
    origins: http://localhost:3000

logger:
  levels:
    io.micronaut.context.condition: INFO
    io.micronaut.data.query: DEBUG